name: repository
favicon: null
layout_spectrum: 1
typography_spectrum: 0.16399
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: thought repository
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73451962-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#26181b'
    - '#0f463f'
    - '#d3c6c6'
    - '#8b5f66'
    - '#fefefe'
  brandStrength: 0.0625
  lightness: 0.375
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
