name: repository
favicon: null
layout_spectrum: 0.9055348413530737
typography_spectrum: 0.8802888500504196
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6005250117741525
  lightness: 0.6369853541254997
  saturation: 0.6691678112838417
  rhythmicContrast: 0.718832477927208
purpose: []
