name: repository
favicon: null
layout_spectrum: 1
typography_spectrum: 0.16399
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: thought repository
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050006'
    - '#f66865'
    - '#fefefe'
    - '#2a48fb'
    - '#9e2039'
  brandStrength: 0.1875
  lightness: 0.375
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
